---
components:
  - name: max31865
    description: Driver for MAX31725/MAX31726 temperature sensors
    group: temperature
    groups:
      - name: humidity
    code_owners: UncleRus
    depends:
      - driver
      - log
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3-Clause
    copyrights:
      - author:
          name: UncleRus
        year: 2021
